### ISSUE TITLE
No contact to the configuration (QGIS 3.13)

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/qgis-dfd-knap#11]
Vi har fået en rapport fra en bruger:

Jeg får en fejl i QGIS 3.13:

```
2020-05-20T10:28:44     WARNING    No contact to the configuration at https://github.com/Septima/qgis-dfd-knap/raw/master/Qlrfile_Datafordeler_QGIS3/DFD-opsaetning_udenBNPW.qlr. Exception:
```
 
Selve exception dukker ikke op

**Comment by GregersP** [comment]
Github har hustlet med nedetid på web-facing ting, men jeg kan kun finde noget dagen inden og efter på deres statusside...

https://www.githubstatus.com/

**Comment by AsgerPetersen** [comment]
Måske det var bedre at hente filen gennem raw.githubusercontent.com ?

**Comment by KKansimm** [comment]
Københavns kommune ville gerne bestille den nødvendig rettelse til dette problematik, så det bliver indbygget i den samlede plugin løsning

**Comment by klavspc** [comment]
>Københavns kommune ville gerne bestille den nødvendig rettelse til dette problematik, så det bliver indbygget i den samlede plugin løsning

Fikset i v. 1.3 - tak til Kbh
