### ISSUE TITLE
Datafordeler plugin er ikke til at finde

### ISSUE THREAD

**Issue by shtirlitsDva** [Septima/qgis-dfd-knap#5]
Hej
Bruger Qgis 3.6 og kan ikke finde Datafordeler plugin når jeg søger i Plugins|All...

Eller skal det være Qgis 3.4 iht. "For QGIS 3.4 fungerer Datafordelerens WFS tjenester med plugin ’Datafordeler-plugin’." citat fra Datafordeler hjemmeside..

**Comment by shtirlitsDva** [comment]
Kan hellere ikke finde det med Qgis 3.4...

**Comment by MieWinstrup** [comment]
Hej,
Vi har ikke endnu lagt pluginet op på QGIS' Plugin Repository. Så indtil videre skal du downloade det her fra Github:
[Datafordeler.zip](https://github.com/Septima/qgis-dfd-knap/files/3012456/Datafordeler.zip)

Download denne mappe og følg vejledningen nederst på denne side:
https://septima.dk/blog/DatafordelerPlugin#da

**Comment by shtirlitsDva** [comment]
Okay, tak. Ville være perfekt hvis dette information også fremgik af Datafordelerens hjemmeside. ;)

**Comment by Andy-KK** [comment]
Her i Københavns kommune går vi over til QGIS 3.6.3, og oplever problemer med datafordeleren plugin. Der er fejl ved opstart af QGIS vedrørende dette kald til jeres proxy service

https://dfd-qgis-wfs-proxy.septima.dk/wfs-meta/geodanmark/capabilities.php?username=XXXX&password=XXXX&SERVICE=WFS&REQUEST=GetCapabilities&ACCEPTVERSIONS=2.0.0,1.1.0,1.0.0 

Kun skærmkort virker (WMS) ikke WFS
Har I et bud en løsning?

**Comment by AsgerPetersen** [comment]
Hej @Andy-KK 

Vi arbejder på at opdatere forbindelsesoplysningerne til Datafordeleren. Det skulle gerne komme til at virke inden for ganske få dage.

Der er sket en del ændringer i QGIS' WFS-understøttelse, så det er lidt af et arbejde at sørge for, at pluginet og den bagvedliggende proxy hele tiden spiller sammen med både QGIS LTR og Datafordeleren.

**Comment by AsgerPetersen** [comment]
Hej @Andy-KK 

Har du mulighed for at prøve med den sidste nye version? Du kan finde information om installation her: https://github.com/Septima/qgis-dfd-knap/blob/master/README.md

Hvis det stadig ikke fungerer må du meget gerne åbne et nyt issue med en beskrivelse af fejlbeskeden.

Jeg lukker dette issue nu, da vi er kommet ret langt off topic ifht :-)
